%该滤波为一个带通滤波，留下1100-5900的频域信号
function Hd = bandpass_filter
%BANDPASS_FILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 01-Dec-2021 13:02:17

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

Fstop1 = 900;         % First Stopband Frequency
Fpass1 = 1100;        % First Passband Frequency
Fpass2 = 5900;        % Second Passband Frequency
Fstop2 = 6100;        % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
